### ISSUE TITLE
Fatal error: Class 'erayalakese\Envato_Market_API' not found 

### ISSUE THREAD

**Issue by NotAmaan** [erayalakese/envato-update-checker#1]
Hey,

Been looking for something like this for a long time now. Thank you for writing this! I am trying to integrate this in my plugin but I'm seeing this error.
"Fatal error: Class 'erayalakese\Envato_Market_API' not found in ......"

This is the code I added in the plugin's main file:

```
require_once( 'updates.php' );
require_once(__DIR__.'/vendor/autoload.php');
new \erayalakese\Envato_Update_Checker(PLUGINNAME, PLUGINSLUG, PLUGINVERSION, REMOTEFILE, APIKEY);
```

Also, yes  I did add the correct information in the last line (plugin name, slug etc). Any thoughts?

Thanks again!

**Comment by erayalakese** [comment]
Hello @aman704 ,

Thank you for your report.  Can you please update your scripts with `composer update` command?

**Comment by NotAmaan** [comment]
Hey,

Yes I was able to fix this when I used composer.

Thanks!
